[package]
name = "spin-sync"
version = "0.0.1"
authors = ["Yoshida Shin <wbcchsyn@gmail.com>"]
edition = "2018"

description = """
Synchronization primitives using spinlock.
The interface resembles std::sync.
rust nightly version is required so far.
"""

keywords = ["spin", "lock", "sync", "mutex", "rwlock"]

license = "MIT"

repository = "https://github.com/wbcchsyn/spin-sync-rs.git"

[badges]
circle-ci = { repository = "https://circleci.com/gh/wbcchsyn/spin-sync-rs" }

[dependencies]
