[package]
name = "spin-lock"
version = "0.0.1"
authors = ["Yoshida Shin <wbcchsyn@gmail.com>"]
edition = "2018"

description = "Synchronization primitives using spinlock. The interface resembles std::sync."

license = "MIT"

repository = "https://github.com/wbcchsyn/spin-lock-rs.git"

[dependencies]
