version: 2
jobs:
    build:
        docker:
            - image: circleci/rust
        steps:
            - run: rustup toolchain install nightly
            - checkout
            - run: cargo '+nightly' test

